# Makefile.mk
# Carlos Santos
# CS 240
# Mike Wilder
# 10/18/19
# This is the makefile for the shell "msh".  It stands for myshell.
# In order to run the shell please first make a  fresh compile of the program
# Simply typing "make" and hitting enter should do the trick.
# To start the "msh" shell type in "./msh" and hit enter.
# If you see the angry face ">:" that means the shell is currently running.
# To exit the shell simply type in the exit command, "exit".
# Please note this is a babyshell. Not all commands will work.

all:
	gcc main.c -w -o msh
